### ISSUE TITLE
Install of GBashLib install_all.sh does not work correct.

### ISSUE THREAD

**Issue by slavict** [SmartSoftDev/GBashLib#19]
if I run ./src/scripts/install_all_goodies.sh from dev branch

`Building dependency tree  
Reading state information... Done
git is already the newest version (1:2.25.1-1ubuntu3.3).
0 upgraded, 0 newly installed, 0 to remove and 17 not upgraded.
Already up to date.
Current branch dev is up to date.
./src/scripts/install_all.sh: line 5: /home/user/ghub/bash/GBashLib/src/install_dependencies.sh: No such file or directory`

**Comment by ghe0Rghe** [comment]
should be fixed in the DEV branch now.
