### ISSUE TITLE
ModuleNotFoundError: No module named 'tabulate'

### ISSUE THREAD

**Issue by slavict** [SmartSoftDev/GBashLib#3]
when i changed to root user i got:
Traceback (most recent call last):
  File "/bin/autoComplete", line 16, in <module>
    from tabulate import tabulate
ModuleNotFoundError: No module named 'tabulate'
root@ghost:/home/ghost# ll /bin/autoComplete

**Comment by ghe0Rghe** [comment]
Ok, let me check the installation script ... maybe the tabulate is not installed with requirements ...

**Comment by slavict** [comment]
I run install again and error disappear but got a warning
/bin/autoComplete:35: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  cfg.config = yaml.load(f)

**Comment by ghe0Rghe** [comment]
`/bin/autoComplete:35: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.`

I know this problem let me repair it ...
